<?php 
/**
 * PAGE global header
 * 
 * @author michael g
 * @author Stura - Referat IT <ref-it@tu-ilmenau.de>
 * @since 17.02.2018
 * @copyright 	Copyright (C) 2018 - All rights reserved
 */
 ?>
<!DOCTYPE html>
<html lang="de">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
		<meta name="description" content="<?= BASE_TITLE ?>" >
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="theme-color" content="#173d92" >
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="mobile-web-app-capable" content="yes">
		<script type="text/javascript">
			var GLOBAL_RELATIVE = "<?= URIBASE; ?>";
		</script>
		<link rel="stylesheet" type="text/css" href="<?= URIBASE ?>css/style.css">
	    <title><?= BASE_TITLE ?></title>
	</head>
	<body id="body">
		<div class="content">
			